# Generated by Django 4.0.3 on 2022-04-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('desc', models.CharField(max_length=120)),
                ('link', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=50)),
            ],
        ),
    ]
