# Generated by Django 4.0.3 on 2022-04-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0002_alter_new_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='desc',
            field=models.CharField(max_length=400),
        ),
    ]
