# Generated by Django 4.0.3 on 2022-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0003_alter_new_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
