# Generated by Django 4.0.3 on 2022-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0004_alter_new_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='ticker',
            field=models.CharField(default='asf', max_length=50),
            preserve_default=False,
        ),
    ]
