# Generated by Django 4.0.3 on 2022-05-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0005_new_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=400)),
                ('model', models.BinaryField()),
                ('BB', models.BooleanField(default=False)),
                ('DEMA', models.BooleanField(default=False)),
                ('RSI', models.BooleanField(default=False)),
                ('MACD', models.BooleanField(default=False)),
            ],
        ),
    ]
