# Generated by Django 4.0.3 on 2022-05-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0006_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='model',
        ),
    ]
