# Generated by Django 4.0.3 on 2022-05-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0008_aimodel_delete_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='scaled',
            field=models.BooleanField(default=False),
        ),
    ]
