# Generated by Django 4.0.3 on 2022-05-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0009_aimodel_scaled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='model',
            field=models.FileField(upload_to=''),
        ),
    ]
