# Generated by Django 4.0.3 on 2022-05-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0011_alter_aimodel_desc_alter_aimodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='model',
            field=models.FileField(upload_to='models'),
        ),
    ]
