# Generated by Django 4.0.3 on 2022-05-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0012_alter_aimodel_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='ticker',
            field=models.CharField(default='d', max_length=50),
        ),
    ]
