# Generated by Django 4.0.3 on 2022-05-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0013_aimodel_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='ticker',
            field=models.CharField(max_length=50),
        ),
    ]
