# Generated by Django 4.0.3 on 2022-05-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0014_alter_aimodel_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='n_lookup',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
