# Generated by Django 4.0.3 on 2022-05-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0015_aimodel_n_lookup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='n_lookup',
            new_name='lookup',
        ),
    ]
