# Generated by Django 4.0.3 on 2022-05-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0017_aimodel_scaler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='scaler',
            field=models.FileField(upload_to='scalers'),
        ),
    ]
