# Generated by Django 4.0.3 on 2022-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0018_alter_aimodel_scaler'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='keras',
            field=models.BooleanField(default=False),
        ),
    ]
