# Generated by Django 4.0.3 on 2022-05-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0019_aimodel_keras'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='news',
            field=models.BooleanField(default=False),
        ),
    ]
