# Generated by Django 4.0.3 on 2022-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0021_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
